apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rrb152zqe-go 
  janus-idp.io/tekton: rrb152zqe-go
  backstage.io/kubernetes-id: rrb152zqe-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rrb152zqe-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  